### ISSUE TITLE
A dependency in META6 file doesn't look right

### ISSUE THREAD

**Issue by hythm7** [JJ/Raku-Digest-HMAC#2]
This [line]( https://github.com/JJ/Raku-Digest-HMAC/blob/master/META6.json#L8) has an extra ":"  after the spec name, should be `Digest:ver<0.18.0+>` instead of `Digest::ver<0.18.0+>`.

**Comment by hythm7** [comment]
Need to bump version as well, so the change can be picked up by REA and module indexers.

**Comment by JJ** [comment]
Will do, but maybe after there's some substantial change. I've created a series of issues #3 #4 #5; any of them could help create a new version.
