### ISSUE TITLE
Test depends on module that doesn't exist.

### ISSUE THREAD

**Issue by ShimmerFairy** [JJ/Raku-Digest-HMAC#6]
META6.json has this line:

```
    "test-depends": ["Digest::SHA"],
```

Which references a "Digest::SHA" module that doesn't appear to exist anywhere, causing zef to fail to install this distribution.

**Comment by JJ** [comment]
That's weird. Let me check.

**Comment by JJ** [comment]
Right, there's  Digest::SHA1 and similar. Thanks!
