### ISSUE TITLE
Breakage because of Digest::HMAC name collision

### ISSUE THREAD

**Issue by 2colours** [JJ/Raku-Digest-HMAC#7]
Related to https://github.com/grondilu/libdigest-raku/issues/35.

Now that the Digest module exposes a Digest::HMAC package, module resolution got broken and this module will fail the test because it actually looks up the other Digest::HMAC.

This could be fixed with stricter `use`s but it's also worth pointing out that all dependents might be affected by the consequences of this name collision.

**Comment by JJ** [comment]
May I ask for some kind of precedence here? This module has been here for ever. Can the other change its name or create an `auth` version?

**Comment by 2colours** [comment]
Actually, there is another related breaking change: there is no `Digest` module now. The testing of this module depends on that module in particular - both the dependency and the used module are "down".

**Comment by JJ** [comment]
Sorry, what do you mean exactly? There's no Digest module exposing Digest::HMAC?

**Comment by JJ** [comment]
I see here: https://github.com/grondilu/libdigest-raku/commit/8854593d2616122853a9af555ce222c7128266cc that the fix includes changing the name to HMAC; the Digest name is kept. Can you please clarify?

**Comment by 2colours** [comment]
This distribution does `use Digest` here and there - however, there is no `Digest` module/namespace anymore.
