### ISSUE TITLE
Missing Digest::MD5 in META6.json?

### ISSUE THREAD

**Issue by rcmlz** [JJ/Raku-Digest-HMAC#8]
On Linux I get:

Digest::HMAC] ===SORRY!=== Error while compiling /tmp/d3ac52c281bb0e70d0d02596efa3b087837b709b.tar.gz/Raku-Digest-HMAC/t/01
Aborting due to test failure: Digest::HMAC:ver<1.0.6>:auth<zef:jjmerelo> (use --force-test to override)
[Digest::HMAC] -basic.t
[Digest::HMAC] Could not find Digest::MD5 in:
[Digest::HMAC]     /tmp/1699633406.7895.753.2580966633129
[Digest::HMAC]     /home/runner/.raku
[Digest::HMAC]     /opt/hostedtoolcache/rakudo/2023.10-02/x86_64/share/perl6/site
[Digest::HMAC]     /opt/hostedtoolcache/rakudo/2023.10-02/x86_64/share/perl6/vendor
[Digest::HMAC]     /opt/hoste
[Digest::HMAC] dtoolcache/rakudo/2023.10-02/x86_64/share/perl6/core
[Digest::HMAC]     CompUnit::Repository::AbsolutePath<2526469925648>
[Digest::HMAC]     CompUnit::Repository::NQP<2526409019272>
[Digest::HMAC]     CompUnit::Repository::Perl5<2526409019312>
[Digest::HMAC] at /tmp/d3ac52c281bb0e70d0d02596efa3b087837b709b.tar.gz/Raku-Digest-HMAC/t/01-basic.t:6

and indeed  Digest::MD5 is used in 01-basic.t but not listed in META6.json

**Comment by JJ** [comment]
Will check this out. Thanks for the report.

**Comment by JJ** [comment]
IIRC, `Digest::MD5` is now part of `Digest`, which is listed. Let me check anyway.

**Comment by JJ** [comment]
The new version should already be available in the ecosystem. It's low-pegged to 1, so it should install the latest one that includes Digest::MD5. I'd appreciate if you checked it, and reopen if the problem persists.
